### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by mat-kainos** [mat-kainos/SEBC#1]

**Comment by mat-kainos** [comment]
Done CM Install Labs - Before You Start

**Comment by mat-kainos** [comment]
Done CM Install Lab - Prepare EC2 or other instances although would prefer to make it in a config manager tool (Terraform + Ansible).

**Comment by mat-kainos** [comment]
Done System Configuration Checks and pushed 1_preinstall.md

**Comment by mat-kainos** [comment]
Done MySQL Replication

**Comment by mat-kainos** [comment]
Done Cluster setup

**Comment by mat-kainos** [comment]
Done bonus lab

**Comment by willwatters** [comment]
Please update and push the files in the Lab folder (https://github.com/alarud/SEBC/tree/master/Cloudera-Bootcamp/SEBC-May2019/installation/labs ).  Once that is done I will review and close off the issue thanks.

**Comment by mat-kainos** [comment]
> Please update and push the files in the Lab folder (https://github.com/alarud/SEBC/tree/master/Cloudera-Bootcamp/SEBC-May2019/installation/labs ). Once that is done I will review and close off the issue thanks.

Done, mistakenly pushed to another folder.

**Comment by willwatters** [comment]
Please upload screenshot of your Cloudera Manager and I can then close this off thanks.

**Comment by mat-kainos** [comment]
> Please upload screenshot of your Cloudera Manager and I can then close this off thanks.

Screenshot uploaded, thanks.

**Comment by willwatters** [comment]
Excellent on successfully completing the first Cloudera Bootcamp Lab - getting AWS infrastructure setup, Cloudera Manager and CDH cluster up and running with DB replication.

Also well documented.
