### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by mat-kainos** [mat-kainos/SEBC#2]

**Comment by mat-kainos** [comment]
Done HDFS folder generation, used teragen and performed local copy by using distcp.

**Comment by mat-kainos** [comment]
Completed HDFS Throughput test

**Comment by mat-kainos** [comment]
Completed snapshot tests task

**Comment by mat-kainos** [comment]
Completed HA Setup

**Comment by mat-kainos** [comment]
Completed CM users

**Comment by willwatters** [comment]
Good work for this lab completion - demonstrating you can use distcp; HDFS command; teragen and terasort performance testing tools; enable HDFS HA and adding and configuring users.
