### ISSUE TITLE
Enterprise Labs

### ISSUE THREAD

**Issue by mat-kainos** [mat-kainos/SEBC#4]

**Comment by mat-kainos** [comment]
Completed treasure hunt

**Comment by mat-kainos** [comment]
Completed minotaur dashboard

**Comment by mat-kainos** [comment]
Completed curl deployment

**Comment by mat-kainos** [comment]
Completed the upgrade, still need to format the readme

**Comment by willwatters** [comment]
Successful completion of Enterprise labs - researching and answering various questions; creating Dashboards and running API commands. Fantastic result getting the CM successfully upgraded from 5.14 > 5.15!
